#!/usr/bin/env php
<?php
/**
 * 控制台入口脚本，引导文件
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);      //标识应用运行在调试模式之下
defined('YII_ENV') or define('YII_ENV', 'dev');     //标识应用的运行环境为开发环境

//注册composer自动加载器
require(__DIR__ . '/vendor/autoload.php');
//包含Yii文件
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

//加载配置文件
$config = require(__DIR__ . '/config/console.php');

//创建、配置、运行一个应用主体，可以通过\Yii::$app在全局范围内访问，主要处理控制台请求
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
